# Generated by Django 5.2.6 on 2026-01-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_question_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("fashion", "Fashion"),
                    ("home", "Home"),
                    ("sports", "Sports"),
                    ("art", "Art"),
                    ("vehicles", "Vehicles"),
                ],
                default="electronics",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="auctionitem",
            index=models.Index(fields=["title"], name="auction_ite_title_201b27_idx"),
        ),
        migrations.AddIndex(
            model_name="auctionitem",
            index=models.Index(
                fields=["current_price"], name="auction_ite_current_1f0f68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auctionitem",
            index=models.Index(
                fields=["ends_at"], name="auction_ite_ends_at_080609_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auctionitem",
            index=models.Index(
                fields=["created_at"], name="auction_ite_created_552374_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auctionitem",
            index=models.Index(
                fields=["-created_at"], name="auction_ite_created_09012e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auctionitem",
            index=models.Index(
                fields=["-ends_at"], name="auction_ite_ends_at_18dad7_idx"
            ),
        ),
    ]
