# Generated by Django 5.2.6 on 2026-01-23 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auctionitem_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the auction was closed", null=True
            ),
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                help_text="Winner of the auction (set when auction closes)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_auctions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="winning_bid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Final winning bid amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="auctionitem",
            index=models.Index(fields=["status"], name="auction_ite_status_203a48_idx"),
        ),
        migrations.AddIndex(
            model_name="auctionitem",
            index=models.Index(
                fields=["winner"], name="auction_ite_winner__8422be_idx"
            ),
        ),
    ]
