# Generated by Django 5.2.6 on 2026-01-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CNY", "Chinese Yuan"),
                    ("INR", "Indian Rupee"),
                    ("KRW", "South Korean Won"),
                    ("TRY", "Turkish Lira"),
                    ("RUB", "Russian Ruble"),
                    ("BRL", "Brazilian Real"),
                    ("MXN", "Mexican Peso"),
                    ("CAD", "Canadian Dollar"),
                    ("AUD", "Australian Dollar"),
                ],
                default="USD",
                help_text="User's preferred currency for display",
                max_length=3,
            ),
        ),
    ]
