# Generated by Django 4.2.27 on 2026-01-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_user_preferred_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("copy-link", "Copy Link"),
                            ("embed", "Embed Code"),
                            ("qr-download", "QR Code Download"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_analytics",
                        to="api.auctionitem",
                    ),
                ),
            ],
            options={
                "db_table": "share_analytics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["auction", "-timestamp"],
                        name="share_analy_auction_3fa389_idx",
                    ),
                    models.Index(
                        fields=["platform", "-timestamp"],
                        name="share_analy_platfor_aaf5a9_idx",
                    ),
                ],
            },
        ),
    ]
