# Generated by Django 5.2.6 on 2026-01-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-placed_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='bidder',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='timestamp',
            new_name='placed_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='is_winning',
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='description',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['title'], name='auction_ite_title_201b27_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['description'], name='auction_ite_descrip_a72dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['ends_at'], name='auction_ite_ends_at_080609_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['current_price'], name='auction_ite_current_1f0f68_idx'),
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reply',
            table=None,
        ),
    ]
